### ISSUE TITLE
SEHException thrown after disposal and reopen

### ISSUE THREAD

**Issue by leesei** [curiosity-ai/rocksdb-sharp#5] opened 2020-11-26 06:34 UTC
Example code is here: https://github.com/leesei/RocksDBExample

It writes data to RocksDb and read data from it after disposing the handle.  
While the code works in \*nix environment, we face this exception on Windows environment.

```
Fatal error. System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at RocksDbSharp.Native.rocksdb_get(IntPtr, IntPtr, Byte[], Int64, IntPtr ByRef, RocksDbSharp.ColumnFamilyHandle)
   at RocksDbSharp.Native.rocksdb_get(IntPtr, IntPtr, Byte[], Int64, RocksDbSharp.ColumnFamilyHandle)
   at RocksDbSharp.RocksDb.Get(Byte[], Int64, RocksDbSharp.ColumnFamilyHandle, RocksDbSharp.ReadOptions)
   at RocksDbSharp.RocksDb.Get(Byte[], RocksDbSharp.ColumnFamilyHandle, RocksDbSharp.ReadOptions)
   at RocksDBExample.Program.Main(System.String[])
```

**Comment by fassadlr** [comment] 2021-05-10 15:14
Hi, we are also seeing this exact problem. Any comments from the developers?

**Comment by fassadlr** [comment] 2021-05-10 15:24
@warrenfalk @theolivenbaum

**Comment by fassadlr** [comment] 2021-05-10 17:53
Thanks for getting back to me @theolivenbaum. Yes all of our issues comes from Windows environments. We are running a crypto currency wallet which utilizes your datastore in a multi threaded environment (www.stratisplatform.com).

I dont have any text logs but the issue reported by @leesei is exactly we receive on some Windows environments. I have not experienced personally this issue and @leesei code to reproduce also works fine for me.

Here is an example screenshot:

![unknown (1)](https://user-images.githubusercontent.com/4281271/117702923-0d9b0600-b1c1-11eb-8c2d-c8d2a34d9b72.png)

**Comment by dangershony** [comment] 2021-05-18 21:24
We are experiencing this as well @checho1989 @turcol @sondreb in windows 
https://github.com/block-core/blockcore/issues/341

**Comment by leesei** [comment] 2021-05-22 14:23
From our experience it may be related to the length of value.
We've to go down one level to use LevelDB (pun intended) in our project due to time contraint.
Sorry for not being able to invest more time to reproduce the issue.
But I'll keep an eye on this issue and looking forward for a fix.

**Comment by khalluudi** [comment] 2021-06-24 09:39
I am experiencing the same issue as well. Loading 10 million rows into rocksdb on an Azure VM with Standard SSD LRS storage. On my local physical machine with normal SSD drive, all 10 million rows are loaded fine. However, on the VM, the exception above is thrown. 

It would be great to know what the issue is and if there is a workaround.

**Comment by khalluudi** [comment] 2021-06-25 12:40
So I found out that this issue is due to out of memory issues on the VM in Azure. I am using WriteBatch for bulk load and flushing it for every 10 million rows. When I reduced the flush batch size to one million, it ran without any issues.

**Comment by theolivenbaum** [comment] 2021-07-01 20:24
@leesei I finally have a way to reproduce this - hit it when testing our software on my wife's laptop! Will investigate and come back to you asap!

@khalluudi I think you might have hit a separate issue with the same Interop error code. But nice to hear you found a solution!

**Comment by theolivenbaum** [comment] 2021-07-13 13:54
@leesei quick update, we found a few more machines that hit the same issue on our side. I tested it against old versions, and it seems like the issue we have was introduced on version 6.20.3.

[6.11.4.12240](https://www.nuget.org/packages/RocksDB/6.11.4.12240) works
[6.14.5.13874](https://www.nuget.org/packages/RocksDB/6.14.5.13874) works
[6.15.5.15759](https://www.nuget.org/packages/RocksDB/6.15.5.15759) works
[6.17.3.16253](https://www.nuget.org/packages/RocksDB/6.17.3.16253) works
[6.20.3.19177](https://www.nuget.org/packages/RocksDB/6.20.3.19177) doesn't work

But I'm not sure this is the same issue that you have, as we hit it on DB.Open already.

In any case, could you do the same test changing the version and see if you can find out which version breaks?

**Comment by leesei** [comment] 2021-07-20 07:43
This issue is weirder than I think.

On the original machine that I used to reproduce the issue (A, Windows 10 Home, i7-4930K):

6.11.4.12240 works
6.14.5.13874 works  !!! different behavior, previous crash with 6.14.5.13874 (the version in leesei/RocksDBExample)
6.15.5.15759 doesn't work
6.17.3.16253 doesn't work
6.20.3.19177 doesn't work

On another machine (B, Windows 10 Home, i7-7800X):

6.11.4.12240 works
6.14.5.13874 works
6.15.5.15759 works
6.17.3.16253 works
6.20.3.19177 works

Both machines are relatively recent in terms of Windows update
Not sure if this is related, B has Windows 21H1 installed, and A does not
What else can I dump from the environment?

**Comment by oleg2k** [comment] 2021-12-22 13:00
Crashes when executing code below.
Setting Compression.No eliminate crashes (remember to delete corrupted Db).

    public static void Main()
    {
        for (var i = 1; i <= 1000; i++)
        {
            Console.Write($"iteration {i}...");
            RocksCrashTest();
            Console.WriteLine(" passed.");
        }
        Console.WriteLine("done");
    }

    private static readonly byte[] Data = { 0, 0, 0, 1 };

    static void RocksCrashTest()
    {
        var dbo = new DbOptions()
            .SetCreateIfMissing()
            .SetCreateMissingColumnFamilies();

        var cfo = new ColumnFamilyOptions();

        // prevent crashes and database corruptions by setting "Compression.No"
        // cfo.SetCompression(Compression.No);

        var cf = new ColumnFamilies()
        {
            { "default", cfo },
        };

        var root = Path.GetTempPath(); // @"E:\RocksData";
        var path = Path.Combine(root, "CrashTest\\test.db");
        Directory.CreateDirectory(path);

        using var db = RocksDb.Open(dbo, path, cf);

        var defaultCf = db.GetColumnFamily("default");

        db.Put(Data, Data, defaultCf);
    }

**Comment by oleg2k** [comment] 2021-12-22 13:42
Moreover, it crashes in a similar way in native.
6.27.3 lib files built on Windows.

#include <iostream>
#include "rocksdb/db.h"

int main()
{
    constexpr char data[4] = { 0,0,0,1 };

    for (auto i = 0;; i++)
    {
        rocksdb::Options dbOptions;
        dbOptions.create_if_missing = true;
        dbOptions.create_missing_column_families = true;

        auto cfOptions = rocksdb::ColumnFamilyOptions();
        cfOptions.OptimizeForPointLookup(16);
        //cfOptions.compression = rocksdb::kNoCompression; // no crash if uncommented

        std::vector<rocksdb::ColumnFamilyDescriptor> cfDescriptors;
        cfDescriptors.emplace_back("default", cfOptions);

        std::vector<rocksdb::ColumnFamilyHandle*> cfHandles;

        rocksdb::DB* db;

        const auto status = rocksdb::DB::Open(dbOptions, R"(E:\RocksData\ConsoleApplication31\test.db)", cfDescriptors, &cfHandles, &db);

        if (!status.ok())
        {
            std::cout << status.ToString() << "\n";
            break;
        }

        const auto stateCf = cfHandles[0];

        db->Put(rocksdb::WriteOptions(), stateCf, data, data);

        delete db;

        std::cout << i << "\n";
    }
}

**Comment by AllegraMcdonnell123** [comment] 2022-04-04 07:01
hi, 
does anyone know if the reproduces in the newest version of rocksdb? :) 
@leesei @oleg2k @theolivenbaum

**Comment by fmarkor** [comment] 2022-04-04 16:49
This is a strange one indeed.

We've tried downgrading versions and we've tried upgrading versions. In every case, your wrapper will run the first time on one of our employees Windows machine, however _when he tries to re-open the daemon_ (i.e. after data is written to disk), an SEH exception gets thrown and we're stuck only knowing that `rocksdb_open_column_families` threw an error somehow.

The machine where it fails to re-open the database is a Windows 10, 64-bit install running on an Intel Core i5 2320.

It should be mentioned that the code runs flawlessly on 5 other machines its been tested on.

Here's the full stacktrace:
```Fatal error. System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at RocksDbSharp.Native.rocksdb_open_column_families(IntPtr, System.String, Int32, System.String[], IntPtr[], IntPtr[])
   at RocksDbSharp.RocksDb.Open(RocksDbSharp.DbOptions, System.String, RocksDbSharp.ColumnFamilies)
   at Discreet.DB.DisDB..ctor(System.String)
   at Discreet.DB.DisDB.Initialize()
   at Discreet.DB.DisDB.GetDB()
   at Discreet.Daemon.TXPool..ctor()
   at Discreet.Daemon.TXPool.Initialize()
   at Discreet.Daemon.TXPool.GetTXPool()
   at Discreet.Daemon.Daemon..ctor()
   at Discreet.Program+<Main>d__3.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.__Canon ByRef)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.__Canon ByRef)
   at Discreet.Program.Main(System.String[])
   at Discreet.Program.<Main>(System.String[])
```

We're currently looking into if this is something that can be fixed or if we'll have to abandon the wrapper entirely until it's in a more stable state. The unfortunate thing is that we cannot get more information that the error occured at `open_column_families` in the native DLL. We get a similar error on another developers Arch Linux machine.

Hopefully @warrenfalk @theolivenbaum or someone else might have an idea of what's wrong? :)

**Comment by theolivenbaum** [comment] 2022-04-16 09:06
Hi @fmarkor! We're seeing the same issues on some machines, and in our case this can be easily tracked down to CPUs lacking AVX2. Are you seeing the same thing on your side?
I was wondering recently if this is due to the compression-related imports when compiling RockDB - seems like @oleg2k was spot on the issue! I'll follow from here to see if there is any missing flags for the imports that disable their use of AVX2, otherwise I'll just do the same and set compression to No when running on AVX2-less CPUs. Luckily this can be easily detected on C#.

**Comment by theolivenbaum** [comment] 2022-04-16 09:42
Let's see what happens: https://github.com/curiosity-ai/rocksdb-sharp/commit/2626ca16200253e38c976de3309092d016c83d9c

**Comment by fmarkor** [comment] 2022-04-16 12:39
AVX2 did indeed seem to be the determining factor, thank you so much @theolivenbaum!
However, purely from C# I'm having trouble finding out if we can detect is AVX2 is supported from .NET 6 (i.e. multiplatform generalized checks), rather than Windows-specific ones.

Do you happen to know if there's any namespace that can do the equivalent of `IsProcessorFeaturePresent` without Windows-specific P/Invoke?

**Comment by theolivenbaum** [comment] 2022-04-16 12:46
There's is, it's actually quite simple, you can use something like this:

System.Runtime.Intrinsics.X86.Avx2.IsSupported

It's actually quite nice when writing C# optimized code as checks are optimized away on jitting so there's no performance impact in runtime.

You can check for other instruction sets too using the Intrinsics namespace

**Comment by theolivenbaum** [comment] 2022-04-16 13:29
Just found something interesting!
https://github.com/microsoft/vcpkg/issues/15794

**Comment by theolivenbaum** [comment] 2022-04-16 14:12
Let's see - using my own vcpkg registry now to see if this works, if so I can send the port upstream to vcpkg
https://github.com/curiosity-ai/vcpkg-registry

**Comment by theolivenbaum** [comment] 2022-04-16 16:05
This might be finally fixed on the latest release! It seems like our usage of vcpkg for windows builds was introducing the unwanted dependency on avx2

**Comment by fmarkor** [comment] 2022-04-16 22:11
I believe @theolivenbaum was spot on when he said AVX2 was blocking the dependency. He had me test it on one of my employees machine who uses an older CPU and previously had the above described problems, and it worked with compression **enabled**. Thank you so much @oleg2k and @theolivenbaum for working with me on this issue. I believe this can be consider a closed matter now.

![jFeVq3f](https://user-images.githubusercontent.com/37598270/163692818-fa05bbda-01e1-4c8b-ad95-f768c13ad177.png)

**Comment by theolivenbaum** [comment] 2022-04-20 06:03
Closing this for now, it anyone still hits it with the latest versions please let us know!

**Comment by theolivenbaum** [comment] 2022-06-10 06:56
Reported again by some of our users - so reopening :(

**Comment by fmarkor** [comment] 2022-06-10 07:19
@theolivenbaum Did you get the specifications (OS/hardware)/version the users running into this problem was having? We have gotten it to run on both Linux and all versions of Windows (back to 7) and have had no issues using version 7.1.1.2841 - I'd be happy to have me/our team look into this issue with you.

**Comment by theolivenbaum** [comment] 2022-06-28 17:22
I think the issue they're seeing now is actually related to non-ASCII characters on the DB path. I'm trying to fix this with https://github.com/curiosity-ai/rocksdb-sharp/commit/539e7f95fd82c4fe288380a04d82ba75f7e43f3a, let's see!

**Closed** 2022-06-28 18:17 UTC
